# Generated by Django 6.0.1 on 2026-01-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='e.g. Senior Graphic Designer', max_length=100),
        ),
    ]
