# Generated by Django 6.0.1 on 2026-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_profile_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company you own or work for', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_link',
            field=models.URLField(blank=True, help_text='Link to a live project or App ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], db_index=True, default='freelancer', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='tools',
            field=models.CharField(blank=True, help_text='Comma-separated tools (e.g. Figma, Jira, VS Code)', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
