# Generated by Django 6.0.1 on 2026-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0003_profile_company_name_profile_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='headline',
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available for work'), ('open', 'Open to offers'), ('busy', 'Currently busy')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='english_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent'), ('native', 'Native/Bilingual')], default='fluent', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='project_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tools',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
