# Generated by Django 4.2 on 2025-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0004_profile_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='News', max_length=50)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d')),
                ('excerpt', models.TextField(help_text='Short summary for the card')),
                ('content', models.TextField(help_text='Full article content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
