# Generated by Django 6.0.1 on 2026-01-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_profile_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='e.g. Senior Python Developer', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tools',
            field=models.CharField(blank=True, help_text='Comma separated tools (e.g. Jira, Figma)', max_length=255),
        ),
    ]
