# Generated by Django 6.0.1 on 2026-03-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0010_conversation_message_conversation_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talents.contract'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('refund', 'Refund')], max_length=20),
        ),
    ]
