# Generated by Django 6.0.1 on 2026-03-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0012_alter_message_options_remove_message_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='talents.profile'),
        ),
    ]
